In [10]:
import numpy as np
import sys

In [27]:
# multiply
a = np.array([1,2,3], dtype='int32')

In [19]:
b= np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [20]:
# Get dimension
b.ndim

2

In [14]:
# Get shape
b.shape

(2, 3)

In [21]:
a.dtype

dtype('int32')

In [31]:
# Get Size
a.itemsize

8

In [30]:
# Get Total size - a.nbyptes = a.size * a.itemsize
a.nbytes 

12

# Accessing/Changing sepcific elements, rows, columns etc

In [36]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [40]:
# Get a specific element [ row, column]
a[1,5]

13

In [41]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [48]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [51]:
a[1,5] = 20
print(a)
a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [53]:
b = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [60]:
# Get specific element (work outside in)
b[0,1,1]

4

In [64]:
b[:,1,:] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays

In [66]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [68]:
# All 1s matrix
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [70]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [76]:
# Any other number (full_like)
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [80]:
# Random decimal number
np.random.rand(4,2)

array([[0.48970657, 0.80004551],
       [0.17297942, 0.16437858],
       [0.27522629, 0.08692866],
       [0.5414133 , 0.95787528]])

In [83]:
# Random decimal number2
np.random.random_sample(a.shape)

array([[9.57872991e-02, 2.50275230e-01, 4.77016817e-01, 6.61246250e-04,
        2.06470990e-01, 6.85611196e-01, 1.20882104e-01],
       [3.01101457e-02, 3.77673147e-01, 6.72975651e-01, 6.65871563e-01,
        4.47199172e-01, 8.67429776e-03, 7.44111600e-01]])

In [109]:
# Randome Integer values
np.random.randint(-4, 7, size=(3,3))

array([[ 6, -4, -3],
       [ 4,  2, -3],
       [-3,  2,  6]])

In [111]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [118]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [132]:
# my answer
a = np.ones((5,5), dtype="int")
a[1:4, 1:4] = 0
a[2,2] = 9
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [134]:
# ohter answer
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
output

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be careful when copying arrays!!

In [138]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics
[numpy maths](https://numpy.org/doc/stable/reference/routines.math.html)


In [139]:
a = np.array([1,2,3,4])

In [144]:
a +=2
a

array([3, 4, 5, 6])

In [141]:
a-2

array([-1,  0,  1,  2])

In [142]:
a*2

array([2, 4, 6, 8])

In [143]:
a /2

array([0.5, 1. , 1.5, 2. ])

In [146]:
b = np.array([1,0,1,0])
print(a)
a+b

[3 4 5 6]


array([4, 4, 6, 6])

In [151]:
a**2

array([ 9, 16, 25, 36], dtype=int32)

In [152]:
# Take the sin, cos
print(np.sin(a))
print(np.cos(a))

[ 0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[-0.9899925  -0.65364362  0.28366219  0.96017029]


In [ ]:
## Linear Algebra



In [159]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2]
 [2]
 [2]]


array([[6.],
       [6.]])

In [160]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
# reference docs(https://numpy.org/doc/stable/reference/routines.linalg.html)

# determinant
# trace
# singular vector dcomposition
# eigen values
# matrix norm
# inverse

## Statistics

In [163]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [167]:
np.min(stats)

1

In [168]:
np.max(stats, axis=1)

array([3, 6])

In [169]:
np.sum(stats)

21

In [170]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing arrays

In [175]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
print(before.shape)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [176]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [181]:
# horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
h2
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

## Load data from File

In [190]:
filedata = np.genfromtxt('data.txt', delimiter=",")
filedata.astype('int32')
print(filedata)
filedata = filedata.astype('int32')
print(filedata)

[[815. 929. 315. 719. 781. 199. 857. 113.  83. 162. 740. 803. 803. 211.
  113. 168. 672. 402.]
 [146.  54. 761. 474. 603. 590.  63. 796. 505. 638. 448. 651. 479. 385.
  248. 450. 633. 653.]
 [ 44. 809. 765. 117. 867. 891. 449.  63. 333. 758. 715. 271. 824. 639.
  587. 381. 996. 758.]]
[[815 929 315 719 781 199 857 113  83 162 740 803 803 211 113 168 672 402]
 [146  54 761 474 603 590  63 796 505 638 448 651 479 385 248 450 633 653]
 [ 44 809 765 117 867 891 449  63 333 758 715 271 824 639 587 381 996 758]]


## Bolean Masking and Advanced Indexing

In [192]:
filedata >= 500

array([[ True,  True, False,  True,  True, False,  True, False, False,
        False,  True,  True,  True, False, False, False,  True, False],
       [False, False,  True, False,  True,  True, False,  True,  True,
         True, False,  True, False, False, False, False,  True,  True],
       [False,  True,  True, False,  True,  True, False, False, False,
         True,  True, False,  True,  True,  True, False,  True,  True]])

In [195]:
# you can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]
filedata[filedata > 500]

array([815, 929, 719, 781, 857, 740, 803, 803, 672, 761, 603, 590, 796,
       505, 638, 651, 633, 653, 809, 765, 867, 891, 758, 715, 824, 639,
       587, 996, 758])

In [202]:
x1 = np.any(filedata> 500, axis=0)
print(x1)
x2 = np.any(filedata> 500, axis=1)
print(x2)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True]
[ True  True  True]


In [212]:
(~((filedata > 400) & (filedata < 700)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False, False],
       [ True,  True,  True, False, False, False,  True,  True, False,
        False, False, False, False,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True, False, False,  True,  True,  True]])

# Question2

In [226]:
x = [i for i in range(1,31)]
x = np.array(x)
x = x.reshape((6,5))

# 1
x[2:4, 0:2]
# 2
x[[0,1,2,3], [1,2,3,4]]
# 3
x[[0,4,5], 3:] # x[[0,4,5], 3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])